ares.components += z80
ares.components += sn76489
ares.components += ym2413

ares.objects += ares-ms-cpu
ares.objects += ares-ms-vdp
ares.objects += ares-ms-psg
ares.objects += ares-ms-opll
ares.objects += ares-ms-system
ares.objects += ares-ms-cartridge
ares.objects += ares-ms-controller
ares.objects += ares-ms-expansion

$(object.path)/ares-ms-cpu.o:        $(ares.path)/ms/cpu/cpu.cpp
$(object.path)/ares-ms-vdp.o:        $(ares.path)/ms/vdp/vdp.cpp
$(object.path)/ares-ms-psg.o:        $(ares.path)/ms/psg/psg.cpp
$(object.path)/ares-ms-opll.o:       $(ares.path)/ms/opll/opll.cpp
$(object.path)/ares-ms-system.o:     $(ares.path)/ms/system/system.cpp
$(object.path)/ares-ms-cartridge.o:  $(ares.path)/ms/cartridge/cartridge.cpp
$(object.path)/ares-ms-controller.o: $(ares.path)/ms/controller/controller.cpp
$(object.path)/ares-ms-expansion.o:  $(ares.path)/ms/expansion/expansion.cpp
