ares.components += z80
ares.components += tms9918
ares.components += ay38910

ares.objects += ares-myvision-cpu
ares.objects += ares-myvision-vdp
ares.objects += ares-myvision-psg
ares.objects += ares-myvision-system
ares.objects += ares-myvision-cartridge

$(object.path)/ares-myvision-cpu.o:        $(ares.path)/myvision/cpu/cpu.cpp
$(object.path)/ares-myvision-vdp.o:        $(ares.path)/myvision/vdp/vdp.cpp
$(object.path)/ares-myvision-psg.o:        $(ares.path)/myvision/psg/psg.cpp
$(object.path)/ares-myvision-system.o:     $(ares.path)/myvision/system/system.cpp
$(object.path)/ares-myvision-cartridge.o:  $(ares.path)/myvision/cartridge/cartridge.cpp
