ares.components += mos6502

ares.objects += ares-a26-system
ares.objects += ares-a26-controller
ares.objects += ares-a26-cartridge
ares.objects += ares-a26-cpu
ares.objects += ares-a26-tia
ares.objects += ares-a26-riot

$(object.path)/ares-a26-system.o:     	$(ares.path)/a26/system/system.cpp
$(object.path)/ares-a26-controller.o: 	$(ares.path)/a26/controller/controller.cpp
$(object.path)/ares-a26-cartridge.o:  	$(ares.path)/a26/cartridge/cartridge.cpp
$(object.path)/ares-a26-cpu.o:     		$(ares.path)/a26/cpu/cpu.cpp
$(object.path)/ares-a26-tia.o:     		$(ares.path)/a26/tia/tia.cpp
$(object.path)/ares-a26-riot.o:     	$(ares.path)/a26/riot/riot.cpp
