[package]
name = "librashader-build-script"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
cbindgen = "0.26.0"
clap = { version = "=4.1.0", features = ["derive"] }


[package.metadata.release]
release = false
