ares.components += z80
ares.components += ay38910

ares.objects += ares-spec-keyboard ares-spec-expansion ares-spec-system
ares.objects += ares-spec-cpu ares-spec-ula ares-spec-psg
ares.objects += ares-spec-tape

$(object.path)/ares-spec-keyboard.o:   $(ares.path)/spec/keyboard/keyboard.cpp
$(object.path)/ares-spec-expansion.o:  $(ares.path)/spec/expansion/expansion.cpp
$(object.path)/ares-spec-system.o:     $(ares.path)/spec/system/system.cpp
$(object.path)/ares-spec-cpu.o:        $(ares.path)/spec/cpu/cpu.cpp
$(object.path)/ares-spec-ula.o:        $(ares.path)/spec/ula/ula.cpp
$(object.path)/ares-spec-psg.o:        $(ares.path)/spec/psg/psg.cpp
$(object.path)/ares-spec-tape.o:       $(ares.path)/spec/tape/tape.cpp