ares.components += sm83
ares.components += m93lcx6

ares.objects += ares-gb-system
ares.objects += ares-gb-bus
ares.objects += ares-gb-cartridge
ares.objects += ares-gb-cpu
ares.objects += ares-gb-ppu
ares.objects += ares-gb-apu

$(object.path)/ares-gb-system.o:    $(ares.path)/gb/system/system.cpp
$(object.path)/ares-gb-cartridge.o: $(ares.path)/gb/cartridge/cartridge.cpp
$(object.path)/ares-gb-bus.o:       $(ares.path)/gb/bus/bus.cpp
$(object.path)/ares-gb-cpu.o:       $(ares.path)/gb/cpu/cpu.cpp
$(object.path)/ares-gb-ppu.o:       $(ares.path)/gb/ppu/ppu.cpp
$(object.path)/ares-gb-apu.o:       $(ares.path)/gb/apu/apu.cpp
