ares.components += z80
ares.components += tms9918
ares.components += v9938
ares.components += ay38910
ares.components += ym2413

ares.objects += ares-msx-system
ares.objects += ares-msx-keyboard
ares.objects += ares-msx-cartridge
ares.objects += ares-msx-controller
ares.objects += ares-msx-cpu
ares.objects += ares-msx-vdp
ares.objects += ares-msx-psg

$(object.path)/ares-msx-system.o:     $(ares.path)/msx/system/system.cpp
$(object.path)/ares-msx-keyboard.o:   $(ares.path)/msx/keyboard/keyboard.cpp
$(object.path)/ares-msx-cartridge.o:  $(ares.path)/msx/cartridge/cartridge.cpp
$(object.path)/ares-msx-controller.o: $(ares.path)/msx/controller/controller.cpp
$(object.path)/ares-msx-cpu.o:        $(ares.path)/msx/cpu/cpu.cpp
$(object.path)/ares-msx-vdp.o:        $(ares.path)/msx/vdp/vdp.cpp
$(object.path)/ares-msx-psg.o:        $(ares.path)/msx/psg/psg.cpp
