ares.components += m68000
ares.components += z80
ares.components += ym2610
ares.components += ym2612
ares.components += ym2149

ares.objects += ares-ng-system
ares.objects += ares-ng-cpu
ares.objects += ares-ng-apu
ares.objects += ares-ng-lspc
ares.objects += ares-ng-opnb
ares.objects += ares-ng-cartridge
ares.objects += ares-ng-controller
ares.objects += ares-ng-card

$(object.path)/ares-ng-system.o:     $(ares.path)/ng/system/system.cpp
$(object.path)/ares-ng-cpu.o:        $(ares.path)/ng/cpu/cpu.cpp
$(object.path)/ares-ng-apu.o:        $(ares.path)/ng/apu/apu.cpp
$(object.path)/ares-ng-lspc.o:       $(ares.path)/ng/lspc/lspc.cpp
$(object.path)/ares-ng-opnb.o:       $(ares.path)/ng/opnb/opnb.cpp
$(object.path)/ares-ng-cartridge.o:  $(ares.path)/ng/cartridge/cartridge.cpp
$(object.path)/ares-ng-controller.o: $(ares.path)/ng/controller/controller.cpp
$(object.path)/ares-ng-card.o:       $(ares.path)/ng/card/card.cpp
