//started: 2020-04-28

#include <n64/memory/memory.cpp>
#include <n64/system/system.cpp>
#include <n64/cartridge/cartridge.cpp>
#include <n64/cic/cic.cpp>
#include <n64/controller/controller.cpp>
#include <n64/dd/dd.cpp>
#include <n64/mi/mi.cpp>
#include <n64/vi/vi.cpp>
#include <n64/ai/ai.cpp>
#include <n64/pi/pi.cpp>
#include <n64/pif/pif.cpp>
#include <n64/ri/ri.cpp>
#include <n64/si/si.cpp>
#include <n64/rdram/rdram.cpp>
#include <n64/cpu/cpu.cpp>
#include <n64/rsp/rsp.cpp>
#include <n64/rdp/rdp.cpp>
#include <n64/aleck64/aleck64.hpp>

//#include <n64/vulkan/parallel-rdp/parallel-rdp/command_ring.cpp>
//#include <n64/vulkan/parallel-rdp/parallel-rdp/rdp_device.cpp>
//#include <n64/vulkan/parallel-rdp/parallel-rdp/rdp_dump_write.cpp>
//#include <n64/vulkan/parallel-rdp/parallel-rdp/rdp_renderer.cpp>
//#include <n64/vulkan/parallel-rdp/parallel-rdp/video_interface.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/buffer.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/buffer_pool.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/command_buffer.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/command_pool.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/context.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/cookie.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/descriptor_set.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/device.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/event_manager.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/fence.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/fence_manager.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/image.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/indirect_layout.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/memory_allocator.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/pipeline_event.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/query_pool.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/render_pass.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/sampler.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/semaphore.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/semaphore_manager.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/shader.cpp>
//#include <n64/vulkan/parallel-rdp/vulkan/texture/texture_format.cpp>
//#include <n64/vulkan/parallel-rdp/util/arena_allocator.cpp>
//#include <n64/vulkan/parallel-rdp/util/logging.cpp>
//#include <n64/vulkan/parallel-rdp/util/thread_id.cpp>
//#include <n64/vulkan/parallel-rdp/util/aligned_alloc.cpp>
//#include <n64/vulkan/parallel-rdp/util/timer.cpp>
//#include <n64/vulkan/parallel-rdp/util/timeline_trace_file.cpp>
//#include <n64/vulkan/parallel-rdp/util/thread_name.cpp>
//#include <n64/vulkan/parallel-rdp/util/environment.cpp>
//#include <n64/vulkan/parallel-rdp/volk/volk.c>
