ares.components += tlcs900h
ares.components += z80
ares.components += t6w28

ares.objects += ares-ngp-system
ares.objects += ares-ngp-cartridge
ares.objects += ares-ngp-cpu
ares.objects += ares-ngp-apu
ares.objects += ares-ngp-kge
ares.objects += ares-ngp-psg

$(object.path)/ares-ngp-system.o:    $(ares.path)/ngp/system/system.cpp
$(object.path)/ares-ngp-cartridge.o: $(ares.path)/ngp/cartridge/cartridge.cpp
$(object.path)/ares-ngp-cpu.o:       $(ares.path)/ngp/cpu/cpu.cpp
$(object.path)/ares-ngp-apu.o:       $(ares.path)/ngp/apu/apu.cpp
$(object.path)/ares-ngp-kge.o:       $(ares.path)/ngp/kge/kge.cpp
$(object.path)/ares-ngp-psg.o:       $(ares.path)/ngp/psg/psg.cpp
