ares.components += m68k
ares.components += z80
ares.components += sn76489
ares.components += ym2612

ares.objects += ares-md-cpu
ares.objects += ares-md-apu
ares.objects += ares-md-vdp
ares.objects += ares-md-psg
ares.objects += ares-md-opn2
ares.objects += ares-md-mcd
ares.objects += ares-md-system
ares.objects += ares-md-cartridge
ares.objects += ares-md-expansion
ares.objects += ares-md-controller

$(object.path)/ares-md-cpu.o:        $(ares.path)/md/cpu/cpu.cpp
$(object.path)/ares-md-apu.o:        $(ares.path)/md/apu/apu.cpp
$(object.path)/ares-md-vdp.o:        $(ares.path)/md/vdp/vdp.cpp
$(object.path)/ares-md-psg.o:        $(ares.path)/md/psg/psg.cpp
$(object.path)/ares-md-opn2.o:       $(ares.path)/md/opn2/opn2.cpp
$(object.path)/ares-md-mcd.o:        $(ares.path)/md/mcd/mcd.cpp
$(object.path)/ares-md-system.o:     $(ares.path)/md/system/system.cpp
$(object.path)/ares-md-cartridge.o:  $(ares.path)/md/cartridge/cartridge.cpp
$(object.path)/ares-md-expansion.o:  $(ares.path)/md/expansion/expansion.cpp
$(object.path)/ares-md-controller.o: $(ares.path)/md/controller/controller.cpp
