sync:
	@rm -rf ./parallel-rdp
	git clone https://github.com/ares-emu/parallel-rdp.git
	@rm -rf ./parallel-rdp/.git

sync-upstream:
	@rm -rf ./parallel-rdp
	git clone https://github.com/Themaister/parallel-rdp-standalone.git ./parallel-rdp
	@rm -rf ./parallel-rdp/.git
