ares.components += z80
ares.components += tms9918
ares.components += sn76489

ares.objects += ares-pencil2-cpu
ares.objects += ares-pencil2-vdp
ares.objects += ares-pencil2-psg
ares.objects += ares-pencil2-system
ares.objects += ares-pencil2-cartridge
ares.objects += ares-pencil2-controller

$(object.path)/ares-pencil2-cpu.o:        $(ares.path)/pencil2/cpu/cpu.cpp
$(object.path)/ares-pencil2-vdp.o:        $(ares.path)/pencil2/vdp/vdp.cpp
$(object.path)/ares-pencil2-psg.o:        $(ares.path)/pencil2/psg/psg.cpp
$(object.path)/ares-pencil2-system.o:     $(ares.path)/pencil2/system/system.cpp
$(object.path)/ares-pencil2-cartridge.o:  $(ares.path)/pencil2/cartridge/cartridge.cpp
$(object.path)/ares-pencil2-controller.o: $(ares.path)/pencil2/controller/controller.cpp
